### ISSUE TITLE
pip install does not work under SudachiPy 0.6.x environment / SudachiPy 0.6.x の環境下で pip install が通らない

### ISSUE THREAD

**Issue by Nishihara-Daiki** [WorksApplications/chikkarpy#8]
# temporary solution / 暫定的な解決方法
Install SudachiPy 0.5.4, then chikkarpy, then reinstall the latest version of SudachiPy.
SudachiPy 0.5.4 をインストールしてから、chikkarpy をインストールし、その後 SudachiPy 最新版を再インストールする。

```
pip install sudachipy==0.5.4 --upgrade
pip install sudachidict_core
pip install chikkarpy
pip install sudachipy --upgrade
```

**Comment by t-yamamura** [comment]
This error can be avoided by upgrading to version [v0.1.1](https://github.com/WorksApplications/chikkarpy/releases/tag/v0.1.1) or later.
